#!/usr/bin/env bash
# configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx

sudo nginx start

sudo ufw allow  'Nginx HTTP' #nginx should be listed on port 80
echo "Hello World"> /var/www/html/index.nginx-debian.html
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
