#!/usr/bin/env bash
# This script configures Haproxy load balancer in a server.

sudo apt-get -y update
sudo apt-get install -y haproxy
frontend_configuration="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend juan-web-backend\n"
backend_configuration="backend juan-web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 214845-web-01 54.160.79.1 check\n\tserver 214845-web-02 100.25.15.86 check"
sudo sed -i "20i \\\n$frontend_configuration\n$backend_configuration" /etc/haproxy/haproxy.cfg
sudo service haproxy restart

